
export const mockStage:[number|string, string][][] = [
  [
    ['L', "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    ['L', "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    ['L', "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"]
  ]
];
